#!/bin/bash

echo "=== Cloudflare Environment Variable Check ==="
echo ""
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Select your project"
echo "3. Settings → Environment variables"
echo "4. Check for:"
echo "   - GEMINI_API_KEY"
echo "   - (Optional) LOCAL_LLM_URL"
echo ""
echo "If missing:"
echo "   - Add GEMINI_API_KEY = your_actual_api_key"
echo "   - Redeploy"
echo ""
echo "=== Local Test Command ==="
echo ""
echo "export GEMINI_API_KEY='your_key'"
echo "npm run dev"
echo ""
